configuration:
  working_directory: '/tmp/ytdl-sub-downloads'
  dl_aliases: # TODO: Simplify this when ytdl-sub supports nested aliases
    video: "--preset yt_video"
    video-url: "--youtube.video_url"
    tv-show-name: "--overrides.tv_show_name"
    single-video-with-foldername: "--preset yt_video --youtube.video_url"
    single-video: "--preset yt_video --overrides.tv_show_name 'Video' --youtube.video_url"
    # FIXME: Not working
    # single-video-metadata: "--preset yt_video --ytdl_options.external_downloader ffmpeg --ytdl_options.external_downloader_args {'ffmpeg_i': ['-ss', '00:00:01.00', '-to', '00:00:02.00']} --overrides.tv_show_name 'Metadata' --youtube.video_url"

presets:
  yt_video:
    youtube:
      download_strategy: "video"

    output_options:
      output_directory: "/tv_shows/{tv_show_name_sanitized}"
      file_name: "{episode_path}.{ext}"
      thumbnail_name: "{episode_path}-thumb.{thumbnail_ext}"

    # https://github.com/yt-dlp/yt-dlp/blob/2022.04.08/yt_dlp/YoutubeDL.py#L197
    # TODO: First try to pull a native MP4 version off YouTube, and failing that, transcode to MP4 immediately after downloading:
    # yt-dlp -S res,ext:mp4:m4a --recode mp4 https://www.youtube.com/watch?v=dQw4w9WgXcQ
    ytdl_options:
      format: mp4

    overrides:
      tv_show_name: "OVERRIDE IN SUBSCRIPTION"
      season: "{upload_year}"
      episode: "{upload_month}{upload_day_padded}"
      episode_padded: "{upload_month_padded}{upload_day_padded}"
      episode_file_name: "s{season}e{episode_padded}.{title_sanitized}"
      episode_path: "Season {season}/{episode_file_name}"

    nfo_tags:
      nfo_name: "{episode_path}.nfo"
      nfo_root: "episodedetails"
      tags:
        title: "{title}"
        season: "{season}"
        episode: "{episode}"
        plot: "{description}"
        year: "{upload_year}"
        aired: "{upload_date_standardized}"
        # genre:
        #   - "Comedy"
        #   - "Drama"

    output_directory_nfo_tags:
      nfo_name: "tvshow.nfo"
      nfo_root: "tvshow"
      tags:
        title: "{tv_show_name}"
        plot: "{source_description}"
      kodi_safe: True

    chapters:
      embed_chapters: True
      sponsorblock_categories:
        - "outro"
        - "selfpromo"
        - "preview"
        - "interaction"
        - "sponsor"
        - "music_offtopic"
        - "intro"
      remove_sponsorblock_categories: "all"
      remove_chapters_regex:
        - "Intro"
        - "Outro"
      force_key_frames: False

    subtitles:
      subtitles_name: "{title_sanitized}.{lang}.{subtitles_ext}"
      subtitles_type: "srt"
      embed_subtitles: False
      languages: "en"  # supports list of multiple languages
      allow_auto_generated_subtitles: False

  yt_playlist:
    preset: "yt_video"
    youtube:
      download_strategy: "playlist"
    output_options:
      maintain_download_archive: True

  yt_channel:
    preset: "yt_playlist"
    youtube:
      download_strategy: "channel"
      channel_avatar_path: "poster.jpg"
      channel_banner_path: "fanart.jpg"

  yt_channel_recent:
    preset: "yt_channel"
    youtube:
      after: "now-6months"
    output_options:
      keep_files_after: "now-6months"

  jellyfin_tv_show:
    preset:
      - "jellyfin_tv_show_by_date"
      - "season_by_year__episode_by_month_day"
    overrides:
      # required
      tv_show_name: "32.Gun"
      tv_show_directory: "/tv_shows/{tv_show_name_sanitized}"
      url: "https://youtu.be/m1k3Cpke4yU"
      # can be modified from their default value
      # episode_title: "{upload_date_standardized} - {title}"
      # episode_description: "{webpage_url}"
