configuration:
  working_directory: '/tmp/ytdl-sub-downloads'
  dl_aliases:
    video: "--preset yt_video"
    video-url: "--download.url"
    tv-show-name: "--overrides.tv_show_name"
    single-music-video: "--preset yt_video --overrides.tv_show_name 'Music Video' --download.url"

presets:
  yt_video:
    download:
      download_strategy: "url"

    output_options:
      # output_directory: "/config/first_config/output_videos/{tv_show_name_sanitized}"
      output_directory: "../outputs/{tv_show_name_sanitized}"
      file_name: "{episode_path}.{ext}"
      thumbnail_name: "{episode_path}-thumb.{thumbnail_ext}"

    ytdl_options:
      # explicitly download English metadata
      extractor_args:
        youtube:
          lang:
            - "en"

    overrides:
      tv_show_name: "OVERRIDE IN SUBSCRIPTION"
      season: "{upload_year}"
      episode: "{upload_month}{upload_day_padded}"
      episode_padded: "{upload_month_padded}{upload_day_padded}"
      episode_file_name: "s{season}e{episode_padded}.{title_sanitized}"
      episode_path: "Season {season}/{episode_file_name}"

    nfo_tags:
      nfo_name: "{episode_path}.nfo"
      nfo_root: "episodedetails"
      tags:
        title: "{title}"
        season: "{season}"
        episode: "{episode}"
        year: "{upload_year}"
        aired: "{upload_date_standardized}"

    output_directory_nfo_tags:
      nfo_name: "tvshow.nfo"
      nfo_root: "tvshow"
      tags:
        title: "{tv_show_name}"

  yt_playlist:
    preset: "yt_video"
    output_options:
      maintain_download_archive: True
    ytdl_options:
      break_on_existing: True

  yt_channel:
    preset: "yt_playlist"
    download:
      download_strategy: "url"
      playlist_thumbnails:
        - name: "poster.jpg"
          uid: "avatar_uncropped"
        - name: "banner.jpg"
          uid: "banner_uncropped"

  recent_videos:
    date_range:
      after: "now-6months"
    output_options:
      keep_files_after: "now-6months"
