configuration:
  working_directory: '/tmp/ytdl-sub-downloads'
  dl_aliases:
    video: "--preset yt_video"
    video-url: "--download.url"
    type: "--overrides.video_type"
    single-music-video: "--preset yt_video --overrides.video_type 'Music Video' --download.url"
    # FIXME: Not working with `dl` command
    custom-config: "--config '/home/ilker/Documents/MyRepos/youtube-downloader/configs/config.yaml'"

# All example presets are included in this default config.yaml,
# feel free to change it as you see fit. For a detailed explanation
# of the examples, see https://ytdl-sub.readthedocs.io/en/latest/examples.html
presets:
  yt_video:
    download:
      download_strategy: "url"

    output_options:
      output_directory: "../outputs"
      file_name: "{video_path}.{ext}"
      thumbnail_name: "{video_path}.{thumbnail_ext}"

    overrides:
      video_name: "{upload_date_standardized}.{title_sanitized}"
      video_type: "{channel}"
      video_path: "{video_type_sanitized}/{video_name}"

  yt_playlist:
    preset:
      - "yt_video"

    output_options:
      maintain_download_archive: True

    ytdl_options:
      break_on_existing: True

  yt_channel:
    preset:
      - "yt_playlist"

  recent_videos:
    date_range:
      after: "now-6months"
    output_options:
      keep_files_after: "now-6months"


  # #############################################################################
  # # Downloads single videos and stores them as Kodi/Jellyfin/Emby music videos,
  # # which all live in a single directory.
  # yt_music_video:
  #   youtube:
  #     download_strategy: "video"

  #   output_options:
  #     output_directory: "{music_video_directory}"
  #     file_name: "{music_video_name}.{ext}"
  #     thumbnail_name: "{music_video_name}-thumb.jpg"

  #   nfo_tags:
  #     nfo_name: "{music_video_name}.nfo"
  #     nfo_root: "musicvideo"
  #     tags:
  #       artist: "{artist}"
  #       title: "{title}"
  #       album: "Music Videos"
  #       year: "{upload_year}"

  #   overrides:
  #     music_video_directory: "/music_videos"
  #     music_video_name: "{artist_sanitized} - {title_sanitized}"
  #     # artist: # FILL THIS OUT IN THE SUBSCRIPTION

  # #############################################################################
  # # Downloads playlists and stores all videos as Kodi/Jellyfin/Emby music
  # # videos, which all live in a single directory.
  # yt_music_video_playlist:
  #   preset: "yt_music_video"
  #   youtube:
  #     download_strategy: "playlist"

  #   output_options:
  #     maintain_download_archive: True
