metadata:
  preset: "yt_video"
  youtube:
    video_url: "https://www.youtube.com/watch?v=VfzPPyF1qKU"
  ytdl_options:
    # skip_download: true
    external_downloader: ffmpeg
    external_downloader_args: {'ffmpeg_i': ['-ss', '00:00:01.00', '-to', '00:00:02.00']}
  overrides:
    tv_show_name: "Uncategorized"

# jellyfin_video:
#   preset: "jellyfin_tv_show"
#   overrides:
#     tv_show_name: "Jellyfin_TvShow"
#     url: "https://youtu.be/m1k3Cpke4yU"

# a_ride_through_mcu:
# # rick_a_music_video_playlist:
#   preset: "yt_playlist"
#   youtube:
#     # playlist_url: "https://www.youtube.com/playlist?list=PLlaN88a7y2_plecYoJxvRFTLHVbIVAOoc"
#     playlist_url: "https://youtube.com/playlist?list=PLpT1Gph26DnTXXPEcl-havUPokmJGR-lh"
#   overrides:
#     tv_show_name: "A Ride Thorough MCU"

# rick_a_channel:
#   preset: "yt_channel_recent"
#   youtube:
#     channel_url: "https://www.youtube.com/channel/UCuAXFkgsw1L7xaCfnd5JJOw"
#   overrides:
#     tv_show_name: "Rick Astley"
